manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: cornix-shield
      url-base: https://github.com/hitsmaxft
    - name: urob
      url-base: https://github.com/urob

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main         # ZMK 本体
      import:
        file: app/west.yml

    - name: zmk-keyboard-cornix
      remote: cornix-shield  # Cornix のボード定義
      revision: main

    - name: zmk-helpers
      remote: urob           # 便利マクロ集
      revision: main

  self:
    path: config
